#!/bin/bash

cd /build/QGIS
mkdir build
cd build

cmake /build/QGIS -GNinja -DWITH_STAGED_PLUGINS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DWITH_GRASS=OFF -DWITH_GRASS7=OFF -DSUPPRESS_QT_WARNINGS=ON -DENABLE_TESTS=ON -DWITH_QSPATIALITE=OFF -DWITH_QWTPOLAR=OFF -DWITH_APIDOC=OFF -DWITH_ASTYLE=OFF -DWITH_DESKTOP=OFF -DWITH_SERVER=ON -DWITH_SERVER_PLUGINS=ON -DWITH_BINDINGS=ON -DWITH_QTMOBILITY=OFF -DWITH_QUICK=OFF -DWITH_3D=OFF -DWITH_GUI=ON -DDISABLE_DEPRECATED=ON  -DSERVER_SKIP_ECW=ON -DWITH_GEOREFERENCER=OFF
ninja
